//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.detail;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class DiscussApproveActivity_
    extends DiscussApproveActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String GROUPID_EXTRA = "groupid";
    public final static String STATUS_EXTRA = "status";
    public final static String DATAID_EXTRA = "dataid";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.discuss_approve);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        afterInject();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static DiscussApproveActivity_.IntentBuilder_ intent(Context context) {
        return new DiscussApproveActivity_.IntentBuilder_(context);
    }

    public static DiscussApproveActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new DiscussApproveActivity_.IntentBuilder_(fragment);
    }

    public static DiscussApproveActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new DiscussApproveActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        copyApprove = ((LinearLayout) hasViews.findViewById(id.copyLayout));
        cancle = ((Button) hasViews.findViewById(id.writeCancle));
        copyer = ((TextView) hasViews.findViewById(id.copyers));
        commit = ((Button) hasViews.findViewById(id.writeCommit));
        totalCount = ((TextView) hasViews.findViewById(id.totalcount));
        contentEdit = ((EditText) hasViews.findViewById(id.progressEdit));
        approver = ((TextView) hasViews.findViewById(id.approvers));
        addNextApprove = ((LinearLayout) hasViews.findViewById(id.addLayout));
        title = ((TextView) hasViews.findViewById(id.writeTitle));
        {
            View view = hasViews.findViewById(id.addLayout);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DiscussApproveActivity_.this.addClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.writeCancle);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DiscussApproveActivity_.this.cancle();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.writeCommit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DiscussApproveActivity_.this.commit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.copyLayout);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DiscussApproveActivity_.this.copyClick();
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) hasViews.findViewById(id.progressEdit));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                        DiscussApproveActivity_.this.onTextChangesOnHelloTextView(s, view, before, start, count);
                    }

                    @Override
                    public void afterTextChanged(Editable s) {
                    }

                }
                );
            }
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(GROUPID_EXTRA)) {
                groupid = extras_.getString(GROUPID_EXTRA);
            }
            if (extras_.containsKey(STATUS_EXTRA)) {
                status = extras_.getString(STATUS_EXTRA);
            }
            if (extras_.containsKey(DATAID_EXTRA)) {
                dataid = extras_.getString(DATAID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  1 :
                DiscussApproveActivity_.this.onaddApprove(resultCode, data);
                break;
            case  2 :
                DiscussApproveActivity_.this.onaddCopy(resultCode, data);
                break;
        }
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DiscussApproveActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, DiscussApproveActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, DiscussApproveActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DiscussApproveActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public DiscussApproveActivity_.IntentBuilder_ groupid(String groupid) {
            intent_.putExtra(GROUPID_EXTRA, groupid);
            return this;
        }

        public DiscussApproveActivity_.IntentBuilder_ status(String status) {
            intent_.putExtra(STATUS_EXTRA, status);
            return this;
        }

        public DiscussApproveActivity_.IntentBuilder_ dataid(String dataid) {
            intent_.putExtra(DATAID_EXTRA, dataid);
            return this;
        }

    }

}
