//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.detail;

import java.io.Serializable;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import com.handmark.pulltorefresh.library.PullToRefreshListView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import com.yxst.epic.yixin.view.ResizeLayout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ProgressDiscussActivity_
    extends ProgressDiscussActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String DETAIL_LIST_EXTRA = "detailList";
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.detail_progress_discuss);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        aferInject();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ProgressDiscussActivity_.IntentBuilder_ intent(Context context) {
        return new ProgressDiscussActivity_.IntentBuilder_(context);
    }

    public static ProgressDiscussActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ProgressDiscussActivity_.IntentBuilder_(fragment);
    }

    public static ProgressDiscussActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ProgressDiscussActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        footview = ((DiscussFootView_) hasViews.findViewById(id.discussFoot));
        wholeLayout = ((ResizeLayout) hasViews.findViewById(id.wholeLayout));
        listview = ((PullToRefreshListView) hasViews.findViewById(id.discussList));
        {
            View view = hasViews.findViewById(id.writeCancle);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProgressDiscussActivity_.this.cancle();
                    }

                }
                );
            }
        }
        afterView();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(DETAIL_LIST_EXTRA)) {
                detailList = ((DetailList) extras_.getSerializable(DETAIL_LIST_EXTRA));
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public void initViews() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ProgressDiscussActivity_.super.initViews();
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ProgressDiscussActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProgressDiscussActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProgressDiscussActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ProgressDiscussActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ProgressDiscussActivity_.IntentBuilder_ detailList(DetailList detailList) {
            intent_.putExtra(DETAIL_LIST_EXTRA, ((Serializable) detailList));
            return this;
        }

    }

}
