//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.detail;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.LinearLayout;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ProgressFootView_
    extends ProgressFootView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public ProgressFootView_(Context context) {
        super(context);
        init_();
    }

    public ProgressFootView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public ProgressFootView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static ProgressFootView build(Context context) {
        ProgressFootView_ instance = new ProgressFootView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.progress_foot_view, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        afterInject();
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static ProgressFootView build(Context context, AttributeSet attrs) {
        ProgressFootView_ instance = new ProgressFootView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static ProgressFootView build(Context context, AttributeSet attrs, int defStyle) {
        ProgressFootView_ instance = new ProgressFootView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        progressview = ((ImageView) hasViews.findViewById(id.imgP));
        remind = ((LinearLayout) hasViews.findViewById(id.remind));
        progress = ((LinearLayout) hasViews.findViewById(id.progress));
        plan = ((LinearLayout) hasViews.findViewById(id.plan));
        {
            View view = hasViews.findViewById(id.progress);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProgressFootView_.this.progressClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.remind);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProgressFootView_.this.remindClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.plan);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProgressFootView_.this.planClick();
                    }

                }
                );
            }
        }
        afterView();
    }

}
