//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.person;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import com.yxst.epic.yixin.preference.CachePrefs_;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class PersonHome_
    extends PersonHome
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String M_UID_EXTRA = "mUid";
    public final static String M_USER_CODE_EXTRA = "mUserCode";
    public final static String M_NAME_EXTRA = "mName";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.person_home_activity);
    }

    private void init_(Bundle savedInstanceState) {
        mCachePrefs = new CachePrefs_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PersonHome_.IntentBuilder_ intent(Context context) {
        return new PersonHome_.IntentBuilder_(context);
    }

    public static PersonHome_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PersonHome_.IntentBuilder_(fragment);
    }

    public static PersonHome_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PersonHome_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mSexImg = ((ImageView) hasViews.findViewById(id.person_home_id_sex));
        mMsgButton = ((Button) hasViews.findViewById(id.frame_me_id_send_msg));
        mDynamicButton = ((Button) hasViews.findViewById(id.person_home_id_dynamic));
        mTitleText = ((TextView) hasViews.findViewById(id.person_home_id_user_title));
        mDepartText = ((TextView) hasViews.findViewById(id.person_home_id_user_depart));
        mCallButton = ((Button) hasViews.findViewById(id.person_home_id_call_phone));
        mWorkButton = ((Button) hasViews.findViewById(id.person_home_id_work));
        mDetailButton = ((Button) hasViews.findViewById(id.person_home_id_detail));
        talkButton = ((Button) hasViews.findViewById(id.personHomeTalk));
        mUserHeadImg = ((ImageView) hasViews.findViewById(id.person_home_id_head_img));
        mUserText = ((TextView) hasViews.findViewById(id.person_home_id_user_name));
        mEmailButton = ((Button) hasViews.findViewById(id.frame_me_id_send_email));
        button = ((Button) hasViews.findViewById(id.person_home_id_back));
        mGroupText = ((TextView) hasViews.findViewById(id.person_home_id_user_group));
        mOtherLayout = ((LinearLayout) hasViews.findViewById(id.person_home_id_other_layout));
        crateData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(M_UID_EXTRA)) {
                mUid = extras_.getString(M_UID_EXTRA);
            }
            if (extras_.containsKey(M_USER_CODE_EXTRA)) {
                mUserCode = extras_.getString(M_USER_CODE_EXTRA);
            }
            if (extras_.containsKey(M_NAME_EXTRA)) {
                mName = extras_.getString(M_NAME_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PersonHome_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PersonHome_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PersonHome_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PersonHome_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public PersonHome_.IntentBuilder_ mUid(String mUid) {
            intent_.putExtra(M_UID_EXTRA, mUid);
            return this;
        }

        public PersonHome_.IntentBuilder_ mUserCode(String mUserCode) {
            intent_.putExtra(M_USER_CODE_EXTRA, mUserCode);
            return this;
        }

        public PersonHome_.IntentBuilder_ mName(String mName) {
            intent_.putExtra(M_NAME_EXTRA, mName);
            return this;
        }

    }

}
