//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.view;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.CompoundButton.OnCheckedChangeListener;
import android.widget.ImageView;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ContactItemView_
    extends ContactItemView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public ContactItemView_(Context context) {
        super(context);
        init_();
    }

    public ContactItemView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public ContactItemView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    public static ContactItemView build(Context context) {
        ContactItemView_ instance = new ContactItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.list_item_contact, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static ContactItemView build(Context context, AttributeSet attrs) {
        ContactItemView_ instance = new ContactItemView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static ContactItemView build(Context context, AttributeSet attrs, int defStyle) {
        ContactItemView_ instance = new ContactItemView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        viewDivider = ((View) hasViews.findViewById(id.viewDivider));
        mCheckBox = ((CheckBox) hasViews.findViewById(id.cb));
        mIconIV = ((ImageView) hasViews.findViewById(id.iv_icon));
        mNameTV = ((TextView) hasViews.findViewById(id.tv_name));
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.cb));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        ContactItemView_.this.onCheckedChanged(buttonView, isChecked);
                    }

                }
                );
            }
        }
    }

}
