//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.adapter;

import android.content.Context;

public final class ChatListAdapter_
    extends ChatListAdapter
{

    private Context context_;

    private ChatListAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static ChatListAdapter_ getInstance_(Context context) {
        return new ChatListAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
