//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.adapter;

import android.content.Context;

public final class ChatAdapter_
    extends ChatAdapter
{

    private Context context_;

    private ChatAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static ChatAdapter_ getInstance_(Context context) {
        return new ChatAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
