//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.adapter;

import android.content.Context;

public final class ContactListAdapter_
    extends ContactListAdapter
{

    private Context context_;

    private ContactListAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static ContactListAdapter_ getInstance_(Context context) {
        return new ContactListAdapter_(context);
    }

    private void init_() {
        context = context_;
        afterInject();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
