//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.adapter;

import android.content.Context;

public final class ContactSelectAdapter_
    extends ContactSelectAdapter
{

    private Context context_;

    private ContactSelectAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static ContactSelectAdapter_ getInstance_(Context context) {
        return new ContactSelectAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
