//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.adapter;

import android.content.Context;

public final class ContactSearchAdapter_
    extends ContactSearchAdapter
{

    private Context context_;

    private ContactSearchAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static ContactSearchAdapter_ getInstance_(Context context) {
        return new ContactSearchAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
