//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.fragment;

import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.miicaa.home.R.layout;
import com.yxst.epic.yixin.adapter.ContactListAdapter_;
import com.yxst.epic.yixin.data.dto.response.GetOrgInfoResponse;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import org.springframework.web.client.RestClientException;
import za.co.immedia.pinnedheaderlistview.PinnedHeaderListView;

public final class ContactListFragment_
    extends ContactListFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    public final static String IS_SELECT_MODE_ARG = "isSelectMode";
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_contact_list, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
        mContactListAdapter = ContactListAdapter_.getInstance_(getActivity());
        afterInject();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ContactListFragment_.FragmentBuilder_ builder() {
        return new ContactListFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mListView = ((PinnedHeaderListView) hasViews.findViewById(android.R.id.list));
        afterViews();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey(IS_SELECT_MODE_ARG)) {
                isSelectMode = args_.getBoolean(IS_SELECT_MODE_ARG);
            }
        }
    }

    @Override
    public void onPostExecute(final GetOrgInfoResponse response) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ContactListFragment_.super.onPostExecute(response);
            }

        }
        );
    }

    @Override
    public void onPreExecute() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ContactListFragment_.super.onPreExecute();
            }

        }
        );
    }

    @Override
    public void onRestClientExceptionThrown(final RestClientException e) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ContactListFragment_.super.onRestClientExceptionThrown(e);
            }

        }
        );
    }

    @Override
    public void getOrgInfoDoInBackground() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("getOrgInfo", 0, "") {


            @Override
            public void execute() {
                try {
                    ContactListFragment_.super.getOrgInfoDoInBackground();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ContactListFragment build() {
            ContactListFragment_ fragment_ = new ContactListFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

        public ContactListFragment_.FragmentBuilder_ isSelectMode(boolean isSelectMode) {
            args_.putBoolean(IS_SELECT_MODE_ARG, isSelectMode);
            return this;
        }

    }

}
