//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.preference;

import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

import android.content.Context;
import android.content.SharedPreferences;

public final class CachePrefs_
    extends SharedPreferencesHelper
{

    private Context context_;

    public CachePrefs_(Context context) {
        super(context.getSharedPreferences("CachePrefs", 0));
        this.context_ = context;
    }

    public CachePrefs_.CachePrefsEditor_ edit() {
        return new CachePrefs_.CachePrefsEditor_(getSharedPreferences());
    }

    public StringPrefField token() {
        return stringField("token", "");
    }

    public StringPrefField uid() {
        return stringField("uid", "");
    }

    public StringPrefField userName() {
        return stringField("userName", "");
    }

    public final static class CachePrefsEditor_
        extends EditorHelper<CachePrefs_.CachePrefsEditor_>
    {


        CachePrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<CachePrefs_.CachePrefsEditor_> token() {
            return stringField("token");
        }

        public StringPrefEditorField<CachePrefs_.CachePrefsEditor_> uid() {
            return stringField("uid");
        }

        public StringPrefEditorField<CachePrefs_.CachePrefsEditor_> userName() {
            return stringField("userName");
        }

    }

}
