//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.yxst.epic.yixin.activity;

import java.io.Serializable;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import com.miicaa.home.R.id;
import com.miicaa.home.R.layout;
import com.yxst.epic.yixin.data.dto.model.Member;
import com.yxst.epic.yixin.data.dto.response.AddOrRemoveContactResponse;
import com.yxst.epic.yixin.data.dto.response.GetMemberResponse;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import org.springframework.web.client.RestClientException;

public final class ContactDetailActivity_
    extends ContactDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String MEMBER_EXTRA = "Member";
    public final static String USER_NAME_EXTRA = "userName";
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_contact_detail_2);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        afterInject();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ContactDetailActivity_.IntentBuilder_ intent(Context context) {
        return new ContactDetailActivity_.IntentBuilder_(context);
    }

    public static ContactDetailActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ContactDetailActivity_.IntentBuilder_(fragment);
    }

    public static ContactDetailActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ContactDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ivStar = ((ImageView) hasViews.findViewById(id.ivStar));
        tvNickName = ((TextView) hasViews.findViewById(id.tvNickName));
        btnSendMsg = ((Button) hasViews.findViewById(id.btnSendMsg));
        tvName = ((TextView) hasViews.findViewById(id.tvName));
        ivAvatar = ((ImageView) hasViews.findViewById(id.ivAvatar));
        tvEmail = ((TextView) hasViews.findViewById(id.tvEmail));
        tvMobile = ((TextView) hasViews.findViewById(id.tvMobile));
        tvSignature = ((TextView) hasViews.findViewById(id.tvSignature));
        {
            View view = hasViews.findViewById(id.layoutMobile);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ContactDetailActivity_.this.onClickMobile(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btnSendMsg);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ContactDetailActivity_.this.onClickBtnSendMsg(view);
                    }

                }
                );
            }
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(MEMBER_EXTRA)) {
                member = ((Member) extras_.getSerializable(MEMBER_EXTRA));
            }
            if (extras_.containsKey(USER_NAME_EXTRA)) {
                userName = extras_.getString(USER_NAME_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public void onRestClientExceptionThrown(final RestClientException e) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ContactDetailActivity_.super.onRestClientExceptionThrown(e);
            }

        }
        );
    }

    @Override
    public void addOrRemoveContactOnPostExecute(final AddOrRemoveContactResponse response) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ContactDetailActivity_.super.addOrRemoveContactOnPostExecute(response);
            }

        }
        );
    }

    @Override
    public void getMemberOnPostExecute(final GetMemberResponse response) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ContactDetailActivity_.super.getMemberOnPostExecute(response);
            }

        }
        );
    }

    @Override
    public void getMemberDoInBackground() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ContactDetailActivity_.super.getMemberDoInBackground();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void addOrRemoveContactDoInBackground() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ContactDetailActivity_.super.addOrRemoveContactDoInBackground();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ContactDetailActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ContactDetailActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ContactDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ContactDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ContactDetailActivity_.IntentBuilder_ member(Member member) {
            intent_.putExtra(MEMBER_EXTRA, ((Serializable) member));
            return this;
        }

        public ContactDetailActivity_.IntentBuilder_ userName(String userName) {
            intent_.putExtra(USER_NAME_EXTRA, userName);
            return this;
        }

    }

}
