//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.miicaa.home.ui.org;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ArrangementPlan_
    extends ArrangementPlan
    implements HasViews
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String TODOID_EXTRA = "todoid";
    public final static String DATAID_EXTRA = "dataid";
    public final static String CLIENTCODE_EXTRA = "clientcode";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ArrangementPlan_.IntentBuilder_ intent(Context context) {
        return new ArrangementPlan_.IntentBuilder_(context);
    }

    public static ArrangementPlan_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ArrangementPlan_.IntentBuilder_(fragment);
    }

    public static ArrangementPlan_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ArrangementPlan_.IntentBuilder_(supportFragment);
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(TODOID_EXTRA)) {
                todoid = extras_.getString(TODOID_EXTRA);
            }
            if (extras_.containsKey(DATAID_EXTRA)) {
                dataid = extras_.getString(DATAID_EXTRA);
            }
            if (extras_.containsKey(CLIENTCODE_EXTRA)) {
                clientcode = extras_.getString(CLIENTCODE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ArrangementPlan_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ArrangementPlan_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ArrangementPlan_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ArrangementPlan_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ArrangementPlan_.IntentBuilder_ todoid(String todoid) {
            intent_.putExtra(TODOID_EXTRA, todoid);
            return this;
        }

        public ArrangementPlan_.IntentBuilder_ dataid(String dataid) {
            intent_.putExtra(DATAID_EXTRA, dataid);
            return this;
        }

        public ArrangementPlan_.IntentBuilder_ clientcode(String clientcode) {
            intent_.putExtra(CLIENTCODE_EXTRA, clientcode);
            return this;
        }

    }

}
